coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 75%
        threshold: 5%
        base: auto

  ignore:
    - "dist/**/*"
    - "coverage/**/*"
    - "test-files/**/*"
    - "test-temp/**/*"
    - "scripts/**/*"
    - "tasks/**/*"
    - ".taskmaster/**/*"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/*.config.js"
    - "**/*.config.ts"
    - "**/debug_test.js"

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true 